version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    steps:
      - checkout
      - run:
          name: Setup Gcloud dependencies
          command: |
            pyenv global 3.5.2 2.7.12
            # python --version
            # which python3
            # echo 'export CLOUDSDK_PYTHON="/opt/circleci/.pyenv/shims/python3"' >> $BASH_ENV
            # echo ${CLOUDSDK_PYTHON}
            # ls -la /usr/bin/python3
            # echo ${CLOUDSDK_PYTHON}
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet components install beta pubsub-emulator kubectl
            mkdir -p /home/circleci/.config/gcloud
